# Generated by Django 5.0.6 on 2024-07-13 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('guest_surname', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(default='000000000', max_length=15)),
                ('guest_count', models.IntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('payment_method', models.CharField(default='cash', max_length=20)),
                ('extras', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite')], max_length=10)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reservations', models.ManyToManyField(related_name='guests', to='reservations.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservation')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(to='reservations.room'),
        ),
    ]
