# Generated by Django 5.0.6 on 2024-07-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_service_remove_reservation_extras_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='services',
            field=models.ManyToManyField(to='reservations.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(choices=[('none', 'Brak - 0 zł'), ('spa', 'Spa - 200 zł'), ('room_service', 'Room Service - 50 zł'), ('parking', 'Parking - 15 zł'), ('gastronomy', 'Gastronomia - 100 zł')], max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
